## To collect data from websites using web scraping and analyze the extracted data to identify useful patterns, trends, and insights using Python, Pandas, and data visualization techniques.

In [28]:
import requests
from bs4 import BeautifulSoup
from tqdm import tqdm
import pandas as pd

In [15]:
res = requests.get(link)

In [19]:
soup = BeautifulSoup(res.text, 'html.parser')

In [23]:
#soup

In [35]:
data=[]
for page in tqdm(range(1,11)):
    link = 'https://quotes.toscrape.com/page/' + str(page)
    res = requests.get(link)
    soup = BeautifulSoup(res.text, 'html.parser')
    for sp in soup.find_all('div',class_='quote'):
        quote= sp.find('span',class_='text').text[1:-1]
        author=sp.find('small').text
        author_id=sp.find('a').get('href')
        tags=[]
        for tag in sp.find_all('a',class_='tag'):
            tags.append(tag.text)
        tags=','.join(tags)
        data.append([quote,author,author_id,tags])

100%|██████████| 10/10 [00:33<00:00,  3.35s/it]

In [36]:
len(data)

100

In [44]:
df=pd.DataFrame(data,columns=['quote','author','author_id','tags'])

In [45]:
df.head()

,quote,author,author_id,tags
0,The world as we have created it is a process o...,Albert Einstein,/author/Albert-Einstein,"change,deep-thoughts,thinking,world"
1,"It is our choices, Harry, that show what we tr...",J.K. Rowling,/author/J-K-Rowling,"abilities,choices"
2,There are only two ways to live your life. One...,Albert Einstein,/author/Albert-Einstein,"inspirational,life,live,miracle,miracles"
3,"The person, be it gentleman or lady, who has n...",Jane Austen,/author/Jane-Austen,"aliteracy,books,classic,humor"
4,"Imperfection is beauty, madness is genius and ...",Marilyn Monroe,/author/Marilyn-Monroe,"be-yourself,inspirational"

In [46]:
df['author_link']='https://quotes.toscrape.com'+df['author_id']

In [47]:
df.head()

,quote,author,author_id,tags,author_link
0,The world as we have created it is a process o...,Albert Einstein,/author/Albert-Einstein,"change,deep-thoughts,thinking,world",https://quotes.toscrape.com/author/Albert-Eins...
1,"It is our choices, Harry, that show what we tr...",J.K. Rowling,/author/J-K-Rowling,"abilities,choices",https://quotes.toscrape.com/author/J-K-Rowling
2,There are only two ways to live your life. One...,Albert Einstein,/author/Albert-Einstein,"inspirational,life,live,miracle,miracles",https://quotes.toscrape.com/author/Albert-Eins...
3,"The person, be it gentleman or lady, who has n...",Jane Austen,/author/Jane-Austen,"aliteracy,books,classic,humor",https://quotes.toscrape.com/author/Jane-Austen
4,"Imperfection is beauty, madness is genius and ...",Marilyn Monroe,/author/Marilyn-Monroe,"be-yourself,inspirational",https://quotes.toscrape.com/author/Marilyn-Monroe

In [53]:
df.to_csv('Quotes.csv', index=False)

The approach of the program will be fairly simple, and it will be easier to understand it in a POINT format:

We’ll import all the necessary libraries.
Set up our URL strings for making a connection using the requests library.
Parsing the available data from the target page using the BeautifulSoup library’s parser.
From the target page, Identify and Extract the classes and tags which contain the information that is valuable to us.
Prototype it for one page using a loop and then apply it to all the pages.